name: Inventory CICD pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'inventory/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: setup the java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'eclipse-temurin'

      - name: build and test
        working-directory: inventory
        run: ./gradlew build
